CREATE DATABASE BINAES;

USE BINAES;

CREATE TABLE ADMINISTRADOR(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Usuario VARCHAR(30) NOT NULL,
	Contraseña VARCHAR(30) NOT NULL
);

CREATE TABLE PISO(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Numero INT NOT NULL
);

CREATE TABLE AREA(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nombre VARCHAR(40) NOT NULL,
	Descripcion VARCHAR(200) NOT NULL,
	Horario DATETIME NOT NULL,
	Responsable VARCHAR(40) NOT NULL,
	Id_Piso INT FOREIGN KEY REFERENCES PISO(Id)
);

CREATE TABLE EVENTO(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Titulo VARCHAR(50) NOT NULL,
	Imagen IMAGE,
	FechaHora_Inicio DATETIME NOT NULL,
	FechaHora_Fin DATETIME NOT NULL,
	CantidadParticipantes INT NOT NULL,
	Id_Area INT FOREIGN KEY REFERENCES AREA(Id)
);

CREATE TABLE OBJETIVO(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Objectivo VARCHAR(200) NOT NULL,
	Id_Evento INT FOREIGN KEY REFERENCES EVENTO(Id)
);

CREATE TABLE COLECCION(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nombre VARCHAR(40) NOT NULL,
	Tipo VARCHAR(40) NOT NULL,
	Genero VARCHAR(40) NOT NULL
);

CREATE TABLE FORMATO(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Tipo VARCHAR(7) NOT NULL
);

CREATE TABLE MATERIAL(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nombre VARCHAR(80) NOT NULL,
	Portada IMAGE NOT NULL,
	Autor VARCHAR(40) NOT NULL,
	Idioma VARCHAR(25) NOT NULL,
	Editorial VARCHAR(40) NOT NULL,
	Fecha_Publicacion DATE NOT NULL,
	Id_Formato INT FOREIGN KEY REFERENCES FORMATO(Id) NOT NULL,
	Id_Coleccion INT FOREIGN KEY REFERENCES COLECCION(Id) NOT NULL
);

CREATE TABLE ETIQUETA(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Codigo VARCHAR(4) NOT NULL,
	Id_Material INT FOREIGN KEY REFERENCES MATERIAL(Id) NOT NULL
);

CREATE TABLE PALABRAS(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Palabra VARCHAR(40) NOT NULL,
	Id_Material INT FOREIGN KEY REFERENCES MATERIAL(id) NOT NULL
);

CREATE TABLE USUARIO(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nombre VARCHAR(40) NOT NULL,
	Direccion VARCHAR(100) NOT NULL,
	Institucion VARCHAR(80) NOT NULL,
	Telefono VARCHAR(9) NOT NULL CHECK(Telefono LIKE '[2|6|7][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]'),
	Correo VARCHAR(80) CHECK(correo LIKE '%@%.%'),
	Fotografia IMAGE NOT NULL,
	Ocupacion VARCHAR(30) NOT NULL
);

CREATE TABLE PRESTAMO(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	FechaHora_Prestamo DATETIME NOT NULL,
	FechaHora_Devolucion DATETIME NOT NULL,
	Id_Material INT FOREIGN KEY REFERENCES MATERIAL(Id) NOT NULL,
	Id_Usuario INT FOREIGN KEY REFERENCES USUARIO(Id) NOT NULL
);

CREATE TABLE RESERVA(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	FechaHora_Reserva DATETIME NOT NULL,
	FechaHora_Prestamo DATETIME NOT NULL,
	FechaHora_Devolucion DATETIME NOT NULL,
	Id_Material INT FOREIGN KEY REFERENCES MATERIAL(Id) NOT NULL,
	Id_Usuario INT FOREIGN KEY REFERENCES USUARIO(Id) NOT NULL
);	